spring: 
  kafka:
    bootstrap-servers:
    - 192.168.234.128:9095
    template:
      default-topic: unicorn-springboot
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    properties:
      sasl.mechanism: PLAIN
      security.protocol: SASL_PLAINTEXT        
server: 
  port: 80   # 定义服务端口

