spring: 
  kafka:
    bootstrap-servers:
    - 192.168.234.128:9095
    template:
      default-topic: unicorn-springboot
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: group-1
    properties:
      sasl.mechanism: PLAIN
      security.protocol: SASL_PLAINTEXT        
server: 
  port: 80   # 定义服务端口

